[package]
name = "openworkers-deno-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.248.0"
tokio = { version = "1.36.0", features = ["full"] }
